-- carts / cart_items ---------------------------------------------------

create table public.carts (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles (id) on delete cascade,
  -- Trimmed from an earlier draft that also had 'abandoned' -- no
  -- abandoned-cart recovery feature has been requested. See DATABASE.md,
  -- carts.
  status text not null default 'active' check (status in ('active', 'converted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index carts_one_active_per_profile_idx
  on public.carts (profile_id)
  where status = 'active';

create trigger carts_touch_updated_at
  before update on public.carts
  for each row execute function public.touch_updated_at();

alter table public.carts enable row level security;

create policy carts_owner_all on public.carts
  for all using (profile_id = auth.uid()) with check (profile_id = auth.uid());

create table public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  -- Numeric, not int, so a future fractional-quantity answer (DECISIONS.md
  -- Q9) isn't blocked -- no fractional UI exists yet.
  quantity numeric(10, 2) not null check (quantity > 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cart_id, product_id)
);

create index cart_items_cart_id_idx on public.cart_items (cart_id);

create trigger cart_items_touch_updated_at
  before update on public.cart_items
  for each row execute function public.touch_updated_at();

alter table public.cart_items enable row level security;

create policy cart_items_owner_all on public.cart_items
  for all using (
    exists (select 1 from public.carts c where c.id = cart_items.cart_id and c.profile_id = auth.uid())
  )
  with check (
    exists (select 1 from public.carts c where c.id = cart_items.cart_id and c.profile_id = auth.uid())
  );

-- orders ------------------------------------------------------------------
-- No direct client INSERT/UPDATE on orders/order_items/order_status_history
-- /payments -- all writes go through the trusted SECURITY DEFINER
-- functions in 0008_trusted_functions.sql. A plain "insert where
-- profile_id = auth.uid()" RLS policy would restrict *which rows* a client
-- can touch, not *which values* -- it would let a client submit a forged
-- unit_price. See DECISIONS.md D18 / ARCHITECTURE.md, Authentication.

create sequence public.orders_number_seq;

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  profile_id uuid not null references public.profiles (id),
  status text not null default 'PENDING' check (
    status in ('PENDING', 'CONFIRMED', 'PREPARING', 'PACKING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED')
  ),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  discount_amount numeric(10, 2) not null default 0 check (discount_amount >= 0),
  total numeric(10, 2) generated always as (subtotal + delivery_fee - discount_amount) stored,
  address_id uuid references public.addresses (id) on delete set null,
  address_snapshot jsonb not null,
  delivery_zone_id uuid references public.delivery_zones (id) on delete set null,
  delivery_time_slot_id uuid references public.delivery_time_slots (id) on delete set null,
  delivery_slot_snapshot jsonb not null,
  payment_method_id uuid references public.payment_methods (id),
  payment_status text not null default 'PENDING' check (
    payment_status in ('PENDING', 'AWAITING_VERIFICATION', 'PAID', 'FAILED', 'REFUNDED')
  ),
  -- Set when this order was generated by a subscription; added now even
  -- though subscription automation isn't built until Phase 9, so no later
  -- backfill of historical orders is needed.
  subscription_id uuid references public.subscriptions (id) on delete set null,
  customer_notes text,
  loyalty_points_earned integer not null default 0,
  loyalty_points_redeemed integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index orders_profile_id_created_at_idx on public.orders (profile_id, created_at desc);
create index orders_subscription_id_idx on public.orders (subscription_id);

create trigger orders_touch_updated_at
  before update on public.orders
  for each row execute function public.touch_updated_at();

alter table public.orders enable row level security;

create policy orders_owner_select on public.orders
  for select using (profile_id = auth.uid());

create policy orders_admin_select on public.orders
  for select using (public.is_admin());

-- order_items --------------------------------------------------------

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  product_name_ar text not null,
  product_name_en text,
  -- Computed exclusively by create_order() from live products.price --
  -- there is no path by which a client supplies this value.
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  quantity numeric(10, 2) not null check (quantity > 0),
  line_total numeric(10, 2) not null check (line_total >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create index order_items_order_id_idx on public.order_items (order_id);

alter table public.order_items enable row level security;

create policy order_items_owner_select on public.order_items
  for select using (
    exists (select 1 from public.orders o where o.id = order_items.order_id and o.profile_id = auth.uid())
  );

create policy order_items_admin_select on public.order_items
  for select using (public.is_admin());

-- order_status_history -------------------------------------------------

create table public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  status text not null,
  changed_by uuid references public.profiles (id),
  note text,
  created_at timestamptz not null default now()
);

create index order_status_history_order_id_created_at_idx on public.order_status_history (order_id, created_at);

alter table public.order_status_history enable row level security;

create policy order_status_history_owner_select on public.order_status_history
  for select using (
    exists (select 1 from public.orders o where o.id = order_status_history.order_id and o.profile_id = auth.uid())
  );

create policy order_status_history_admin_select on public.order_status_history
  for select using (public.is_admin());

-- payments ----------------------------------------------------------
-- 1:N with orders (payment attempts), not 1:1 -- a rejected manual
-- transfer can be resubmitted with a corrected reference. orders.
-- payment_status remains the single authoritative current state. See
-- DECISIONS.md D18 / ARCHITECTURE.md, Payment Abstraction.

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  payment_method_id uuid not null references public.payment_methods (id),
  amount numeric(10, 2) not null check (amount >= 0),
  status text not null default 'PENDING' check (
    status in ('PENDING', 'AWAITING_VERIFICATION', 'VERIFIED', 'REJECTED', 'REFUNDED')
  ),
  transaction_reference text,
  proof_image_url text,
  verified_by uuid references public.profiles (id),
  verified_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index payments_order_id_idx on public.payments (order_id);

create trigger payments_touch_updated_at
  before update on public.payments
  for each row execute function public.touch_updated_at();

alter table public.payments enable row level security;

create policy payments_owner_select on public.payments
  for select using (
    exists (select 1 from public.orders o where o.id = payments.order_id and o.profile_id = auth.uid())
  );

create policy payments_admin_select on public.payments
  for select using (public.is_admin());

-- Table privileges for every table in this migration are centralized in
-- 0010_privilege_lockdown.sql -- see that file's header for why.
